game:
    resource: "@GameBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

hello:
    path:     /hello
    defaults:
        _controller: app.hello_controller:indexAction